//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Backtracking {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Backtracking.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import numpy as np
        ///from timeit import default_timer
        ///
        ///def is_valid(grid, row, col, num):
        ///    # VÃ©rifier si num est prÃ©sent dans la ligne spÃ©cifiÃ©e
        ///    if num in grid[row]:
        ///        return False
        ///    
        ///    # VÃ©rifier si num est prÃ©sent dans la colonne spÃ©cifiÃ©e
        ///    if num in grid[:, col]:
        ///        return False
        ///    
        ///    # VÃ©rifier si num est prÃ©sent dans le bloc 3x3
        ///    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
        ///    for r in range(start_row, start_row + 3):
        ///        for c in range(start_col, st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Backtracking_py {
            get {
                return ResourceManager.GetString("Backtracking.py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import clr
        ///clr.AddReference(&quot;Sudoku.Shared&quot;)
        ///clr.AddReference(&quot;Sudoku.Backtracking&quot;)
        ///from Sudoku.Backtracking import BacktrackingDotNetSolver
        ///netSolver = BacktrackingDotNetSolver()
        ///solvedSudoku = netSolver.Solve(sudoku).
        /// </summary>
        internal static string SelfCallSolver_py {
            get {
                return ResourceManager.GetString("SelfCallSolver.py", resourceCulture);
            }
        }
    }
}
